services:

  nats-server:
    image: nats:latest
  
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-477504/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: pnpm start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-477504/image-registry/products-ms
    ports:
      - ${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}
    # volumes:
    #   - ./products-ms/src:/usr/src/app/src
    # command: pnpm start:dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  
  orders-ms:
    # depends_on:
    #   - orders-db
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-477504/image-registry/orders-ms
    # ports:
    #   - "3002:3002"
    # volumes:
    #   - ./orders-ms/src:/usr/src/app/src
    # command: pnpm start:dev
    environment:
      - PORT=4002
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  # orders-db:
  #   container_name: orders-database
  #   image: postgres:17.4
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: ordersdb
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
    
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-477504/image-registry/payments-ms
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    # volumes:
    #   - ./payments-ms/src:/usr/src/app/src
    # command: pnpm start:dev
    environment:
      - PAYMENTS_MS_PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-477504/image-registry/auth-ms
    # ports:
    #   - "3004:3004"
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    # command: pnpm start:dev
    environment:
      - AUTH_MS_PORT=4004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}